version: "3"
services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - my-network
    volumes:
      - backend-data:/app/backend/data

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:

volumes:
  backend-data:





















